Model:
    name: "PA_KRN"
    depth: None
    pretrained: True
    PM:
        patch_size: 384
        stride: 96

Test:
    Dataset:
        type: "RGB_Dataset"
        root: "data/RGB_Dataset/Test_Dataset"
        sets: ['DUTS-TE', 'DUT-OMRON', 'ECSSD', 'HKU-IS', 'PASCAL-S']
        transforms:
            resize:
                size: [352, 352]
            tonumpy: NULL
            normalize: 
                mean: [104.00699, 116.66877, 122.67892]
                div: 1
            totensor: NULL
        transforms_PM:
            dynamic_resize:
                patch_size: 384
                stride: 192
            tonumpy: NULL
            normalize: 
                mean: [104.00699, 116.66877, 122.67892]
                div: 1
            totensor: NULL
    Dataloader:
        num_workers: 8
        pin_memory: True
    Checkpoint:
        checkpoint_dir: "snapshots/SotA/PA_KRN"

Eval:
    gt_root: "data/RGB_Dataset/Test_Dataset"
    pred_root: "snapshots/SotA/PA_KRN"
    result_path: "results"
    datasets: ['DUTS-TE', 'DUT-OMRON', 'ECSSD', 'HKU-IS', 'PASCAL-S']
    metrics: ['Sm', 'mae', 'adpEm', 'maxEm', 'avgEm', 'adpFm', 'maxFm', 'avgFm', 'wFm']