from lib.InSPyReNet_Res2Net50 import InSPyReNet_Res2Net50
from lib.InSPyReNet_SwinB import InSPyReNet_SwinB
from lib.EInSPyReNet_SwinB import EInSPyReNet_SwinB
from lib.InSPyReNet_SwinBSS import InSPyReNet_SwinBSS